---
title: "git_01"
author: "Sylvia Rodriguez"
date: "09/21/21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
"You are old, father William," the young man said,  
"And your hair has become very white;  
And yet you incessantly stand on your head —  
Do you think, at your age, it is right?"  
"In my youth," father William replied to his son,   


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
When I see birches bend to left and right  
Across the lines of straighter darker trees,  
I like to think some boy’s been swinging them.  
But swinging doesn’t bend them down to stay  
As ice-storms do. Often you must have seen them  



## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
     Shining with all his might:  
He did his very best to make  
 The billows smooth and bright —  
And this was odd, because it was  
 The middle of the night.  

The moon was shining sulkily,  
 Because she thought the sun   
Had got no business to be there   
  After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."   
      

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Over many a quaint and curious volume of forgotten lore—  
    While I nodded, nearly napping, suddenly there came a tapping, 
As of some one gently rapping, rapping at my chamber door.  
“’Tis some visitor,” I muttered, “tapping at my chamber door—  
            Only this and nothing more.”  

    Ah, distinctly I remember it was in the bleak December;  
And each separate dying ember wrought its ghost upon the floor.  
    Eagerly I wished the morrow;—vainly I had sought to borrow  
    From my books surcease of sorrow—sorrow for the lost Lenore—  
For the rare and radiant maiden whom the angels name Lenore—  
            Nameless here for evermore.  

    And the silken, sad, uncertain rustling of each purple curtain 
Thrilled me—filled me with fantastic terrors never felt before;  
    So that now, to still the beating of my heart, I stood repeating  
    “’Tis some visitor entreating entrance at my chamber door—  
Some late visitor entreating entrance at my chamber door;—  
            This it is and nothing more.”  
